import { Share } from 'react-native';
import { IconButton } from './IconButton';

export const ShareButton = ({ title, content, color }) => {
    const date = new Date();
    const shareEmail = async () => {
        const shareContent = {
            title: title + " from Risk",
            message: content + "\nGenerated by the Risk app at " + date.toString() + ".",
        };
        const shareOptions = {
            dialogTitle: title,
            subject: title + " from Risk",
        };
        try {
            await Share.share(shareContent, shareOptions);
        } catch (error) {
            console.error('Error sharing:', error);
        }
    };

    return (
        <IconButton ionicons_name="share-outline" onPress={shareEmail} color={color} size={24} />
    );
};